stages: # 定义了一条pipeline
  - 代码检测 # 定义了stage
  - 单元测试
  - 编译
  #- 发布JAR包

PMD扫描: # 定义了一个job
  stage: 代码检测 # 绑定到stage
  plugin: PMD # 指定使用的插件
  checkRule: # 校验结果
    - pmd1 = 0 && pmd2 = 0

STC扫描:
  stage: 代码检测
  plugin: STC
  checkRule:
    - stc = 0

单元测试:
  stage: 单元测试
  plugin: UT
  checkRule:
    - passRate = 100
  pluginConfig:
    markdown: admin/result.md # 向页面输出一些自定义内容

编译:
  stage: 编译
  plugin: ANT-BUILD         # 使用插件ANT-BUILD
  pluginConfig:
    image: reg.docker.alibaba-inc.com/antb/sofa-build:0.0.2
    script:
      - export PATH=$PATH:/opt/taobao/java/bin:/opt/taobao/maven/bin
      - java -version
      - mvn -version
      - mvn clean package -Dmaven.test.skip=true -Ptest
    outputs:
      - name: registry.tgz
        paths: ["./distribution-enterprise/alipay/target/registry.tgz"]

发布JAR包:
  stage: 发布JAR包
  plugin: ANT-BUILD
  pluginConfig:
    image: reg.docker.alibaba-inc.com/antb/jarbuild:0.0.1
    script:
      - java -version
      - mvn -version
      - sed -i '/<mirrors>/,/<\/mirrors>/d' /opt/taobao/maven_settings/settings-release.xml
      - sed -i '/<profiles>/,/<\/profiles>/d' /opt/taobao/maven_settings/settings-release.xml
      - mvn clean deploy -Dmaven.test.skip=true -s /opt/taobao/maven_settings/settings-release.xml -Ptest -Pantcode-release